/**
 * Relational schema of the profile, for the tables lot 1 needs.
 *
 * The business tables are the state of reference; `domain_events` records provenance beside
 * them, in the same transaction, and is never replayed to rebuild an entity. Identifiers are
 * opaque and generated by the backend. Ordered lists carry a rebalanceable rank rather than
 * a position that has to be renumbered.
 */

import { index, integer, sqliteTable, text, uniqueIndex } from 'drizzle-orm/sqlite-core'

/** A logical grouping that exists before its sources do. */
export const projects = sqliteTable('projects', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  /** Prefix of the future Spec keys; reserved by lot 1, used by lot 2. */
  specKeyPrefix: text('spec_key_prefix'),
  createdAt: integer('created_at').notNull(),
  updatedAt: integer('updated_at').notNull(),
  /** Version the next mutation must expect, so no write silently overwrites another. */
  version: integer('version').notNull().default(1),
})

/**
 * A working environment of a project. `main` carries the physical path; the project itself
 * has none, and `main` is never a removable resource.
 */
export const workspaces = sqliteTable(
  'workspaces',
  {
    id: text('id').primaryKey(),
    projectId: text('project_id')
      .notNull()
      .references(() => projects.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    path: text('path').notNull(),
    createdAt: integer('created_at').notNull(),
  },
  (table) => [uniqueIndex('workspaces_project_name').on(table.projectId, table.name)],
)

/**
 * Where a project keeps its repositories, relative to the root of its workspaces. An empty
 * list means the root itself; nothing is initialised for it.
 */
export const projectRepositories = sqliteTable(
  'project_repositories',
  {
    id: text('id').primaryKey(),
    projectId: text('project_id')
      .notNull()
      .references(() => projects.id, { onDelete: 'cascade' }),
    /** Path relative to the workspace root; never absolute, never leaving the root. */
    relativePath: text('relative_path').notNull(),
    rank: text('rank').notNull(),
  },
  (table) => [uniqueIndex('project_repositories_path').on(table.projectId, table.relativePath)],
)

/** A thread of work belonging to a project, with no Spec and no workspace required. */
export const sessions = sqliteTable(
  'sessions',
  {
    id: text('id').primaryKey(),
    projectId: text('project_id')
      .notNull()
      .references(() => projects.id, { onDelete: 'cascade' }),
    title: text('title').notNull(),
    /** True once the user renamed it, so no proposal overwrites the choice. */
    titleChosen: integer('title_chosen').notNull().default(0),
    /** Absent mission: `free`. Missions arrive with lot 2. */
    mission: text('mission'),
    archivedAt: integer('archived_at'),
    createdAt: integer('created_at').notNull(),
    updatedAt: integer('updated_at').notNull(),
    version: integer('version').notNull().default(1),
  },
  (table) => [index('sessions_project').on(table.projectId, table.archivedAt)],
)

/** One message of a session, ordered by a rebalanceable rank within its session. */
export const sessionEntries = sqliteTable(
  'session_entries',
  {
    id: text('id').primaryKey(),
    sessionId: text('session_id')
      .notNull()
      .references(() => sessions.id, { onDelete: 'cascade' }),
    /** `human` in lot 1; an agent author arrives with lot 2. */
    author: text('author').notNull(),
    body: text('body').notNull(),
    rank: text('rank').notNull(),
    createdAt: integer('created_at').notNull(),
  },
  (table) => [uniqueIndex('session_entries_rank').on(table.sessionId, table.rank)],
)

/**
 * Append-only provenance of the business changes.
 *
 * The sequence is a global, strictly increasing integer that orders events independently of
 * the clock. Correlations used by product reads are indexed columns, never a JSON payload.
 * The Spec, revision and phase correlations are declared for the lots that introduce them
 * and stay empty here.
 */
export const domainEvents = sqliteTable(
  'domain_events',
  {
    sequence: integer('sequence').primaryKey({ autoIncrement: true }),
    type: text('type').notNull(),
    /** Entity the event is mainly about. */
    entity: text('entity').notNull(),
    entityId: text('entity_id').notNull(),
    /** What caused it: the user, or later an agent or a command. */
    source: text('source').notNull(),
    author: text('author').notNull(),
    occurredAt: integer('occurred_at').notNull(),
    projectId: text('project_id'),
    sessionId: text('session_id'),
    /** Declared for lot 2 and beyond; never filled by lot 1. */
    specId: text('spec_id'),
    revisionId: text('revision_id'),
    phaseId: text('phase_id'),
    payload: text('payload'),
  },
  (table) => [
    index('domain_events_project').on(table.projectId, table.sequence),
    index('domain_events_session').on(table.sessionId, table.sequence),
  ],
)

/** Display preferences of the profile, including the theme and the panel sizes. */
export const appPreferences = sqliteTable('app_preferences', {
  key: text('key').primaryKey(),
  value: text('value').notNull(),
  updatedAt: integer('updated_at').notNull(),
})

/** Migrations already applied to this profile, with the fingerprint they were applied from. */
export const schemaMigrations = sqliteTable('schema_migrations', {
  name: text('name').primaryKey(),
  checksum: text('checksum').notNull(),
  appliedAt: integer('applied_at').notNull(),
})
