/**
 * Projects, their `main` workspace, their repository list, their sessions and their messages.
 *
 * Every change and its journal event land in the same transaction. The configuration of a
 * project lives here, in the profile database: nothing is ever written into the folder the
 * user works in, and no repository is initialised there.
 */

import type { Database } from 'bun:sqlite'

import {
  MAIN_WORKSPACE,
  NoActiveProjectError,
  UNTITLED_SESSION,
  messageBody,
  projectName,
  rankBetween,
  repositoryLocations,
  titleAfterMessage,
} from '@hemera/core'
import type { Project, Session, SessionEntry, Workspace } from '@hemera/core'

import { recordChange } from './journal.ts'

export interface Identifiers {
  /** Opaque identifiers, generated by the backend. */
  next: () => string
}

export interface StoreContext {
  database: Database
  ids: Identifiers
  now: number
}

export class UnknownProjectError extends Error {
  constructor(readonly projectId: string) {
    super(`no project with id ${projectId}`)
    this.name = 'UnknownProjectError'
  }
}

export class UnknownSessionError extends Error {
  constructor(readonly sessionId: string) {
    super(`no session with id ${sessionId}`)
    this.name = 'UnknownSessionError'
  }
}

export class VersionConflictError extends Error {
  constructor(
    readonly entity: string,
    readonly expected: number,
    readonly actual: number,
  ) {
    super(`${entity} moved on: expected version ${expected}, found ${actual}`)
    this.name = 'VersionConflictError'
  }
}

interface ProjectRow {
  id: string
  name: string
  created_at: number
  updated_at: number
  version: number
}

interface WorkspaceRow {
  id: string
  project_id: string
  name: string
  path: string
  created_at: number
}

interface SessionRow {
  id: string
  project_id: string
  title: string
  title_chosen: number
  mission: string | null
  archived_at: number | null
  created_at: number
  updated_at: number
  version: number
}

interface EntryRow {
  id: string
  session_id: string
  author: string
  body: string
  rank: string
  created_at: number
}

function toProject(row: ProjectRow): Project {
  return {
    id: row.id,
    name: row.name,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
    version: row.version,
  }
}

function toSession(row: SessionRow): Session {
  return {
    id: row.id,
    projectId: row.project_id,
    title: row.title,
    titleChosen: row.title_chosen === 1,
    mission: 'free',
    archivedAt: row.archived_at,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
    version: row.version,
  }
}

export interface CreatedProject {
  project: Project
  workspace: Workspace
}

/**
 * Creates a project and the `main` workspace carrying its path.
 *
 * The caller has already checked the folder: a project is never created around a path that
 * cannot be read, and no folder is created in the user's place.
 */
export function createProject(
  context: StoreContext,
  input: { name: string; path: string },
): CreatedProject {
  const name = projectName(input.name)
  const project: Project = {
    id: context.ids.next(),
    name,
    createdAt: context.now,
    updatedAt: context.now,
    version: 1,
  }
  const workspace: Workspace = {
    id: context.ids.next(),
    projectId: project.id,
    name: MAIN_WORKSPACE,
    path: input.path,
    createdAt: context.now,
  }

  recordChange(
    context.database,
    {
      type: 'project.created',
      entity: 'project',
      entityId: project.id,
      source: 'user',
      author: 'human',
      occurredAt: context.now,
      projectId: project.id,
    },
    () => {
      context.database.run(
        'INSERT INTO projects (id, name, created_at, updated_at, version) VALUES (?, ?, ?, ?, ?)',
        [project.id, project.name, project.createdAt, project.updatedAt, project.version],
      )
      context.database.run(
        'INSERT INTO workspaces (id, project_id, name, path, created_at) VALUES (?, ?, ?, ?, ?)',
        [workspace.id, workspace.projectId, workspace.name, workspace.path, workspace.createdAt],
      )
    },
  )
  return { project, workspace }
}

export function listProjects(database: Database): Project[] {
  const rows = database.query('SELECT * FROM projects ORDER BY created_at').all() as ProjectRow[]
  return rows.map(toProject)
}

export function findProject(database: Database, projectId: string): Project | null {
  const row = database
    .query('SELECT * FROM projects WHERE id = ?')
    .get(projectId) as ProjectRow | null
  return row === null ? null : toProject(row)
}

/** The `main` workspace of a project, which carries its path. */
export function mainWorkspace(database: Database, projectId: string): Workspace | null {
  const row = database
    .query('SELECT * FROM workspaces WHERE project_id = ? AND name = ?')
    .get(projectId, MAIN_WORKSPACE) as WorkspaceRow | null
  return row === null
    ? null
    : {
        id: row.id,
        projectId: row.project_id,
        name: row.name,
        path: row.path,
        createdAt: row.created_at,
      }
}

export interface ProjectConfiguration {
  name: string
  /** Repository locations, relative to the workspace root. */
  repositories: string[]
}

/** The configuration a project holds, read from the profile. */
export function readConfiguration(database: Database, projectId: string): ProjectConfiguration {
  const project = findProject(database, projectId)
  if (project === null) throw new UnknownProjectError(projectId)
  const rows = database
    .query('SELECT relative_path FROM project_repositories WHERE project_id = ? ORDER BY rank')
    .all(projectId) as { relative_path: string }[]
  return {
    name: project.name,
    repositories: repositoryLocations(rows.map((row) => row.relative_path)),
  }
}

/**
 * Replaces the configuration of a project.
 *
 * The whole configuration is validated before anything is written: a refused configuration
 * leaves the previous one exactly as it was.
 */
export function writeConfiguration(
  context: StoreContext,
  projectId: string,
  expectedVersion: number,
  configuration: { name: string; repositories: readonly string[] },
): Project {
  const project = findProject(context.database, projectId)
  if (project === null) throw new UnknownProjectError(projectId)
  if (project.version !== expectedVersion) {
    throw new VersionConflictError('project', expectedVersion, project.version)
  }

  // Validation happens before the transaction opens, so nothing is half written.
  const name = projectName(configuration.name)
  const declared =
    configuration.repositories.length === 0 ? [] : repositoryLocations(configuration.repositories)

  const updated: Project = {
    ...project,
    name,
    updatedAt: context.now,
    version: project.version + 1,
  }

  recordChange(
    context.database,
    {
      type: 'project.configured',
      entity: 'project',
      entityId: projectId,
      source: 'user',
      author: 'human',
      occurredAt: context.now,
      projectId,
    },
    () => {
      context.database.run(
        'UPDATE projects SET name = ?, updated_at = ?, version = ? WHERE id = ?',
        [updated.name, updated.updatedAt, updated.version, projectId],
      )
      context.database.run('DELETE FROM project_repositories WHERE project_id = ?', [projectId])
      let rank: string | null = null
      for (const relativePath of declared) {
        rank = rankBetween(rank, null)
        context.database.run(
          'INSERT INTO project_repositories (id, project_id, relative_path, rank) VALUES (?, ?, ?, ?)',
          [context.ids.next(), projectId, relativePath, rank],
        )
      }
    },
  )
  return updated
}

/** Creates a `free` session in a project. */
export function createSession(
  context: StoreContext,
  projectId: string | null,
  title = UNTITLED_SESSION,
): Session {
  if (projectId === null) throw new NoActiveProjectError()
  if (findProject(context.database, projectId) === null) throw new UnknownProjectError(projectId)

  const session: Session = {
    id: context.ids.next(),
    projectId,
    title,
    titleChosen: false,
    mission: 'free',
    archivedAt: null,
    createdAt: context.now,
    updatedAt: context.now,
    version: 1,
  }

  recordChange(
    context.database,
    {
      type: 'session.created',
      entity: 'session',
      entityId: session.id,
      source: 'user',
      author: 'human',
      occurredAt: context.now,
      projectId,
      sessionId: session.id,
    },
    () => {
      context.database.run(
        `INSERT INTO sessions
          (id, project_id, title, title_chosen, mission, created_at, updated_at, version)
         VALUES (?, ?, ?, 0, NULL, ?, ?, ?)`,
        [
          session.id,
          projectId,
          session.title,
          session.createdAt,
          session.updatedAt,
          session.version,
        ],
      )
    },
  )
  return session
}

export function listSessions(database: Database, projectId: string): Session[] {
  const rows = database
    .query('SELECT * FROM sessions WHERE project_id = ? ORDER BY created_at')
    .all(projectId) as SessionRow[]
  return rows.map(toSession)
}

export function findSession(database: Database, sessionId: string): Session | null {
  const row = database
    .query('SELECT * FROM sessions WHERE id = ?')
    .get(sessionId) as SessionRow | null
  return row === null ? null : toSession(row)
}

export interface RecordedMessage {
  entry: SessionEntry
  session: Session
}

/**
 * Records a message of a session.
 *
 * The message is durable before it is ever presented as recorded, and the title of a session
 * without one is proposed from it unless the user already chose a title.
 */
export function recordMessage(
  context: StoreContext,
  sessionId: string,
  body: string,
): RecordedMessage {
  const session = findSession(context.database, sessionId)
  if (session === null) throw new UnknownSessionError(sessionId)
  const text = messageBody(body)

  const last = context.database
    .query('SELECT rank FROM session_entries WHERE session_id = ? ORDER BY rank DESC LIMIT 1')
    .get(sessionId) as { rank: string } | null

  const entry: SessionEntry = {
    id: context.ids.next(),
    sessionId,
    author: 'human',
    body: text,
    rank: rankBetween(last === null ? null : last.rank, null),
    createdAt: context.now,
  }
  const title = titleAfterMessage(session, text, last === null)
  const updated: Session = {
    ...session,
    title,
    updatedAt: context.now,
    version: session.version + 1,
  }

  recordChange(
    context.database,
    {
      type: 'session.entry.recorded',
      entity: 'session',
      entityId: sessionId,
      source: 'user',
      author: 'human',
      occurredAt: context.now,
      projectId: session.projectId,
      sessionId,
    },
    () => {
      context.database.run(
        `INSERT INTO session_entries (id, session_id, author, body, rank, created_at)
         VALUES (?, ?, ?, ?, ?, ?)`,
        [entry.id, entry.sessionId, entry.author, entry.body, entry.rank, entry.createdAt],
      )
      context.database.run(
        'UPDATE sessions SET title = ?, updated_at = ?, version = ? WHERE id = ?',
        [updated.title, updated.updatedAt, updated.version, sessionId],
      )
    },
  )
  return { entry, session: updated }
}

/** The messages of a session, in the order they were recorded. */
export function readMessages(database: Database, sessionId: string): SessionEntry[] {
  const rows = database
    .query('SELECT * FROM session_entries WHERE session_id = ? ORDER BY rank')
    .all(sessionId) as EntryRow[]
  return rows.map((row) => ({
    id: row.id,
    sessionId: row.session_id,
    author: row.author as 'human',
    body: row.body,
    rank: row.rank,
    createdAt: row.created_at,
  }))
}

/** Renames a session; the choice is never taken back by a proposal. */
export function renameSession(context: StoreContext, sessionId: string, title: string): Session {
  const session = findSession(context.database, sessionId)
  if (session === null) throw new UnknownSessionError(sessionId)
  const chosen = title.trim().length === 0 ? UNTITLED_SESSION : title.trim()
  const updated: Session = {
    ...session,
    title: chosen,
    titleChosen: true,
    updatedAt: context.now,
    version: session.version + 1,
  }

  recordChange(
    context.database,
    {
      type: 'session.renamed',
      entity: 'session',
      entityId: sessionId,
      source: 'user',
      author: 'human',
      occurredAt: context.now,
      projectId: session.projectId,
      sessionId,
    },
    () => {
      context.database.run(
        'UPDATE sessions SET title = ?, title_chosen = 1, updated_at = ?, version = ? WHERE id = ?',
        [updated.title, updated.updatedAt, updated.version, sessionId],
      )
    },
  )
  return updated
}

/** Archives or restores a session. Nothing is ever deleted. */
export function setSessionArchived(
  context: StoreContext,
  sessionId: string,
  archived: boolean,
): Session {
  const session = findSession(context.database, sessionId)
  if (session === null) throw new UnknownSessionError(sessionId)
  const archivedAt = archived ? context.now : null
  const updated: Session = {
    ...session,
    archivedAt,
    updatedAt: context.now,
    version: session.version + 1,
  }

  recordChange(
    context.database,
    {
      type: archived ? 'session.archived' : 'session.restored',
      entity: 'session',
      entityId: sessionId,
      source: 'user',
      author: 'human',
      occurredAt: context.now,
      projectId: session.projectId,
      sessionId,
    },
    () => {
      context.database.run(
        'UPDATE sessions SET archived_at = ?, updated_at = ?, version = ? WHERE id = ?',
        [archivedAt, updated.updatedAt, updated.version, sessionId],
      )
    },
  )
  return updated
}
