/**
 * Projects, their `main` workspace, their repository list, their sessions and their messages.
 *
 * Every change and its journal event land in the same transaction. The configuration of a
 * project lives here, in the profile database: nothing is ever written into the folder the
 * user works in, and no repository is initialised there.
 *
 * Queries are built from the schema rather than written as SQL text, so a column that moves
 * fails the typecheck instead of returning nothing at run time.
 */

import type { Database } from 'bun:sqlite'
import { and, asc, desc, eq } from 'drizzle-orm'

import {
  MAIN_WORKSPACE,
  NoActiveProjectError,
  UNTITLED_SESSION,
  messageBody,
  projectName,
  rankBetween,
  repositoryLocations,
  titleAfterMessage,
} from '@hemera/core'
import type { Project, Session, SessionEntry, Workspace } from '@hemera/core'

import { recordChange } from './journal.ts'
import { orm } from './orm.ts'
import { projectRepositories, projects, sessionEntries, sessions, workspaces } from './schema.ts'

export interface Identifiers {
  /** Opaque identifiers, generated by the backend. */
  next: () => string
}

export interface StoreContext {
  database: Database
  ids: Identifiers
  now: number
}

export class UnknownProjectError extends Error {
  constructor(readonly projectId: string) {
    super(`no project with id ${projectId}`)
    this.name = 'UnknownProjectError'
  }
}

export class UnknownSessionError extends Error {
  constructor(readonly sessionId: string) {
    super(`no session with id ${sessionId}`)
    this.name = 'UnknownSessionError'
  }
}

export class VersionConflictError extends Error {
  constructor(
    readonly entity: string,
    readonly expected: number,
    readonly actual: number,
  ) {
    super(`${entity} moved on: expected version ${expected}, found ${actual}`)
    this.name = 'VersionConflictError'
  }
}

type ProjectRow = typeof projects.$inferSelect
type SessionRow = typeof sessions.$inferSelect

function toProject(row: ProjectRow): Project {
  return {
    id: row.id,
    name: row.name,
    createdAt: row.createdAt,
    updatedAt: row.updatedAt,
    version: row.version,
  }
}

function toSession(row: SessionRow): Session {
  return {
    id: row.id,
    projectId: row.projectId,
    title: row.title,
    titleChosen: row.titleChosen === 1,
    mission: 'free',
    archivedAt: row.archivedAt,
    createdAt: row.createdAt,
    updatedAt: row.updatedAt,
    version: row.version,
  }
}

export interface CreatedProject {
  project: Project
  workspace: Workspace
}

/**
 * Creates a project and the `main` workspace carrying its path.
 *
 * The caller has already checked the folder: a project is never created around a path that
 * cannot be read, and no folder is created in the user's place.
 */
export function createProject(
  context: StoreContext,
  input: { name: string; path: string },
): CreatedProject {
  const name = projectName(input.name)
  const project: Project = {
    id: context.ids.next(),
    name,
    createdAt: context.now,
    updatedAt: context.now,
    version: 1,
  }
  const workspace: Workspace = {
    id: context.ids.next(),
    projectId: project.id,
    name: MAIN_WORKSPACE,
    path: input.path,
    createdAt: context.now,
  }

  const db = orm(context.database)
  recordChange(
    context.database,
    {
      type: 'project.created',
      entity: 'project',
      entityId: project.id,
      source: 'user',
      author: 'human',
      occurredAt: context.now,
      projectId: project.id,
    },
    () => {
      db.insert(projects)
        .values({ ...project, specKeyPrefix: null })
        .run()
      db.insert(workspaces).values(workspace).run()
    },
  )
  return { project, workspace }
}

export function listProjects(database: Database): Project[] {
  return orm(database).select().from(projects).orderBy(asc(projects.createdAt)).all().map(toProject)
}

export function findProject(database: Database, projectId: string): Project | null {
  const row = orm(database).select().from(projects).where(eq(projects.id, projectId)).get()
  return row === undefined ? null : toProject(row)
}

/** The `main` workspace of a project, which carries its path. */
export function mainWorkspace(database: Database, projectId: string): Workspace | null {
  const row = orm(database)
    .select()
    .from(workspaces)
    .where(and(eq(workspaces.projectId, projectId), eq(workspaces.name, MAIN_WORKSPACE)))
    .get()
  return row === undefined ? null : row
}

export interface ProjectConfiguration {
  name: string
  /** Repository locations, relative to the workspace root. */
  repositories: string[]
}

/** The configuration a project holds, read from the profile. */
export function readConfiguration(database: Database, projectId: string): ProjectConfiguration {
  const project = findProject(database, projectId)
  if (project === null) throw new UnknownProjectError(projectId)
  const rows = orm(database)
    .select({ relativePath: projectRepositories.relativePath })
    .from(projectRepositories)
    .where(eq(projectRepositories.projectId, projectId))
    .orderBy(asc(projectRepositories.rank))
    .all()
  return {
    name: project.name,
    repositories: repositoryLocations(rows.map((row) => row.relativePath)),
  }
}

/**
 * Replaces the configuration of a project.
 *
 * The whole configuration is validated before anything is written: a refused configuration
 * leaves the previous one exactly as it was.
 */
export function writeConfiguration(
  context: StoreContext,
  projectId: string,
  expectedVersion: number,
  configuration: { name: string; repositories: readonly string[] },
): Project {
  const project = findProject(context.database, projectId)
  if (project === null) throw new UnknownProjectError(projectId)
  if (project.version !== expectedVersion) {
    throw new VersionConflictError('project', expectedVersion, project.version)
  }

  // Validation happens before the transaction opens, so nothing is half written.
  const name = projectName(configuration.name)
  const declared =
    configuration.repositories.length === 0 ? [] : repositoryLocations(configuration.repositories)

  const updated: Project = {
    ...project,
    name,
    updatedAt: context.now,
    version: project.version + 1,
  }

  const db = orm(context.database)
  recordChange(
    context.database,
    {
      type: 'project.configured',
      entity: 'project',
      entityId: projectId,
      source: 'user',
      author: 'human',
      occurredAt: context.now,
      projectId,
    },
    () => {
      db.update(projects)
        .set({ name: updated.name, updatedAt: updated.updatedAt, version: updated.version })
        .where(eq(projects.id, projectId))
        .run()
      db.delete(projectRepositories).where(eq(projectRepositories.projectId, projectId)).run()
      let rank: string | null = null
      for (const relativePath of declared) {
        rank = rankBetween(rank, null)
        db.insert(projectRepositories)
          .values({ id: context.ids.next(), projectId, relativePath, rank })
          .run()
      }
    },
  )
  return updated
}

/** Creates a `free` session in a project. */
export function createSession(
  context: StoreContext,
  projectId: string | null,
  title = UNTITLED_SESSION,
): Session {
  if (projectId === null) throw new NoActiveProjectError()
  if (findProject(context.database, projectId) === null) throw new UnknownProjectError(projectId)

  const session: Session = {
    id: context.ids.next(),
    projectId,
    title,
    titleChosen: false,
    mission: 'free',
    archivedAt: null,
    createdAt: context.now,
    updatedAt: context.now,
    version: 1,
  }

  const db = orm(context.database)
  recordChange(
    context.database,
    {
      type: 'session.created',
      entity: 'session',
      entityId: session.id,
      source: 'user',
      author: 'human',
      occurredAt: context.now,
      projectId,
      sessionId: session.id,
    },
    () => {
      db.insert(sessions)
        .values({
          id: session.id,
          projectId,
          title: session.title,
          titleChosen: 0,
          // A mission arrives with lot 2; an absent one reads as `free`.
          mission: null,
          archivedAt: null,
          createdAt: session.createdAt,
          updatedAt: session.updatedAt,
          version: session.version,
        })
        .run()
    },
  )
  return session
}

export function listSessions(database: Database, projectId: string): Session[] {
  return orm(database)
    .select()
    .from(sessions)
    .where(eq(sessions.projectId, projectId))
    .orderBy(asc(sessions.createdAt))
    .all()
    .map(toSession)
}

export function findSession(database: Database, sessionId: string): Session | null {
  const row = orm(database).select().from(sessions).where(eq(sessions.id, sessionId)).get()
  return row === undefined ? null : toSession(row)
}

export interface RecordedMessage {
  entry: SessionEntry
  session: Session
}

/**
 * Records a message of a session.
 *
 * The message is durable before it is ever presented as recorded, and the title of a session
 * without one is proposed from it unless the user already chose a title.
 */
export function recordMessage(
  context: StoreContext,
  sessionId: string,
  body: string,
): RecordedMessage {
  const session = findSession(context.database, sessionId)
  if (session === null) throw new UnknownSessionError(sessionId)
  const text = messageBody(body)

  const db = orm(context.database)
  const last = db
    .select({ rank: sessionEntries.rank })
    .from(sessionEntries)
    .where(eq(sessionEntries.sessionId, sessionId))
    .orderBy(desc(sessionEntries.rank))
    .limit(1)
    .get()

  const entry: SessionEntry = {
    id: context.ids.next(),
    sessionId,
    author: 'human',
    body: text,
    rank: rankBetween(last === undefined ? null : last.rank, null),
    createdAt: context.now,
  }
  const title = titleAfterMessage(session, text, last === undefined)
  const updated: Session = {
    ...session,
    title,
    updatedAt: context.now,
    version: session.version + 1,
  }

  recordChange(
    context.database,
    {
      type: 'session.entry.recorded',
      entity: 'session',
      entityId: sessionId,
      source: 'user',
      author: 'human',
      occurredAt: context.now,
      projectId: session.projectId,
      sessionId,
    },
    () => {
      db.insert(sessionEntries).values(entry).run()
      db.update(sessions)
        .set({ title: updated.title, updatedAt: updated.updatedAt, version: updated.version })
        .where(eq(sessions.id, sessionId))
        .run()
    },
  )
  return { entry, session: updated }
}

/** The messages of a session, in the order they were recorded. */
export function readMessages(database: Database, sessionId: string): SessionEntry[] {
  return orm(database)
    .select()
    .from(sessionEntries)
    .where(eq(sessionEntries.sessionId, sessionId))
    .orderBy(asc(sessionEntries.rank))
    .all()
    .map((row) => ({
      id: row.id,
      sessionId: row.sessionId,
      author: row.author as 'human',
      body: row.body,
      rank: row.rank,
      createdAt: row.createdAt,
    }))
}

/** Renames a session; the choice is never taken back by a proposal. */
export function renameSession(context: StoreContext, sessionId: string, title: string): Session {
  const session = findSession(context.database, sessionId)
  if (session === null) throw new UnknownSessionError(sessionId)
  const chosen = title.trim().length === 0 ? UNTITLED_SESSION : title.trim()
  const updated: Session = {
    ...session,
    title: chosen,
    titleChosen: true,
    updatedAt: context.now,
    version: session.version + 1,
  }

  const db = orm(context.database)
  recordChange(
    context.database,
    {
      type: 'session.renamed',
      entity: 'session',
      entityId: sessionId,
      source: 'user',
      author: 'human',
      occurredAt: context.now,
      projectId: session.projectId,
      sessionId,
    },
    () => {
      db.update(sessions)
        .set({
          title: updated.title,
          titleChosen: 1,
          updatedAt: updated.updatedAt,
          version: updated.version,
        })
        .where(eq(sessions.id, sessionId))
        .run()
    },
  )
  return updated
}

/** Archives or restores a session. Nothing is ever deleted. */
export function setSessionArchived(
  context: StoreContext,
  sessionId: string,
  archived: boolean,
): Session {
  const session = findSession(context.database, sessionId)
  if (session === null) throw new UnknownSessionError(sessionId)
  const archivedAt = archived ? context.now : null
  const updated: Session = {
    ...session,
    archivedAt,
    updatedAt: context.now,
    version: session.version + 1,
  }

  const db = orm(context.database)
  recordChange(
    context.database,
    {
      type: archived ? 'session.archived' : 'session.restored',
      entity: 'session',
      entityId: sessionId,
      source: 'user',
      author: 'human',
      occurredAt: context.now,
      projectId: session.projectId,
      sessionId,
    },
    () => {
      db.update(sessions)
        .set({ archivedAt, updatedAt: updated.updatedAt, version: updated.version })
        .where(eq(sessions.id, sessionId))
        .run()
    },
  )
  return updated
}
