/**
 * A window's link that answers nothing unless a test says what: every call stays on its way, and
 * every stream hears nothing. A test spreads what it plays over it.
 */

import type { Link } from '../src/renderer/link.ts'

const never = <A>(): Promise<A> => new Promise<A>(() => undefined)
const silent = () => () => undefined

export const SILENT_LINK: Link = {
  engineStatus: never,
  onEngineStatus: silent,
  environmentReport: never,
  relaunch: never,
  showLog: never,
  chooseFolder: never,
  preferences: never,
  writePreferences: never,
  projects: never,
  project: never,
  onProjectChanges: silent,
  detectRepositories: never,
  createProject: never,
  setWorkspacesRoot: never,
  setBranchPrefix: never,
  addRepository: never,
  removeRepository: never,
  updateRepository: never,
  repositoryStatus: never,
  remotes: never,
  setRemote: never,
  setBaseBranch: never,
  upToDateBase: never,
  onRepositoryChanges: silent,
  recipe: never,
  saveRecipe: never,
  checkRecipe: never,
  variables: never,
  setVariable: never,
  removeVariable: never,
  revealVariable: never,
  catalogue: never,
  saveCommand: never,
  removeCommand: never,
  checkLine: never,
  runs: never,
  startRun: never,
  stopRun: never,
  restartRun: never,
  runOutput: never,
  onRunChanges: silent,
  needs: never,
  answerNeed: never,
  retryNeed: never,
  mission: never,
  onMissionChanges: silent,
  onNotices: silent,
  chats: never,
  createChat: never,
  renameChat: never,
  sendToChat: never,
  stopChat: never,
  setChatModel: never,
  transcript: never,
  onChatChanges: silent,
  missions: never,
  agents: never,
  modelMarks: never,
  markModel: never,
  roleModels: never,
  setAppRoleModel: never,
  checkAgentUpdates: never,
  updateAgent: never,
  hemeraAuto: never,
  setConsent: never,
  saveJevKey: never,
  removeJevKey: never,
  notificationSettings: never,
  setNotificationKind: never,
  setNotificationSound: never,
  setSoundStyle: never,
  previewSound: never,
  backups: never,
  backUp: never,
  restoreProfile: never,
  retention: never,
  testerFindings: never,
  onDecisions: silent,
  close: () => undefined,
}
