#!/usr/bin/env bun
/**
 * Generates the icon catalogue of the design system, and checks that the interface never
 * stands in for an icon with an emoji or a typographic glyph.
 *
 * Icons are declared in code as SVG markup: nothing is read from a file or downloaded while
 * the application runs. `lucide-static` is a development dependency of the generator only and
 * never enters the bundle.
 *
 *   bun tools/icons.ts --generate   rewrite packages/ui/src/icons/catalog.ts
 *   bun tools/icons.ts              check the interface for emoji used as icons
 */

import { existsSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs'
import { join, relative, resolve } from 'node:path'

/** Icons the lot 1 catalogue declares, by their lucide name. */
export const CATALOGUE = [
  'archive',
  'archive-restore',
  'arrow-up',
  'check',
  'chevron-down',
  'chevron-left',
  'chevron-right',
  'chevron-up',
  'circle-alert',
  'circle-check',
  'circle-x',
  'ellipsis',
  'folder',
  'inbox',
  'info',
  'loader-circle',
  'message-square',
  'minus',
  'panel-left',
  'panel-left-open',
  'pencil',
  'plus',
  'search',
  'settings',
  'square',
  'trash-2',
  'triangle-alert',
  'x',
] as const

/** Directories whose sources must carry no emoji standing in for an icon. */
const SCANNED = ['apps/desktop/src', 'packages/ui/src']

export function camelCaseOf(name: string): string {
  // Lucide numbers some of its icons (`trash-2`), and a digit is no more a separator than a
  // letter is: dropping the dash without raising anything gives a valid identifier.
  return name.replace(/-([a-z0-9])/g, (_, character: string) => character.toUpperCase())
}

/**
 * One-line SVG markup GPUI paints as a monochrome sprite. The stroke colour is a placeholder:
 * the renderer recolours the sprite from the element's `color` style.
 */
export function normaliseMarkup(svg: string): string {
  return svg
    .replaceAll(/<!--[\s\S]*?-->/g, '')
    .replaceAll(/\s*\n\s*/g, ' ')
    .replaceAll(/\s+>/g, '>')
    .replaceAll('currentColor', '#000')
    .replaceAll(/\sclass="[^"]*"/g, '')
    .replaceAll(/\swidth="24"|\sheight="24"/g, '')
    .replaceAll(/\s{2,}/g, ' ')
    .trim()
}

export function generateCatalogue(repositoryRoot: string): string {
  const icons = CATALOGUE.map((name) => {
    const path = join(repositoryRoot, 'node_modules', 'lucide-static', 'icons', `${name}.svg`)
    if (!existsSync(path)) throw new Error(`the lucide icon ${name} does not exist`)
    return { name, markup: normaliseMarkup(readFileSync(path, 'utf8')) }
  })

  const declarations = icons
    .map((icon) => `export const ${camelCaseOf(icon.name)} = '${icon.markup}'`)
    .join('\n\n')
  const entries = icons.map((icon) => `  '${icon.name}': ${camelCaseOf(icon.name)},`).join('\n')

  return `/**
 * Icon catalogue of the design system: lucide icons declared in code as SVG markup.
 *
 * Generated by \`bun tools/icons.ts --generate\` from the lucide-static development
 * dependency. Nothing here is read from a file or downloaded while the application runs, and
 * the icon package never enters the bundle. An icon the catalogue does not declare fails the
 * typecheck by name.
 *
 * Each icon paints as a monochrome sprite: the colour comes from the element's \`color\`
 * style, inherited from the surrounding text.
 */

${declarations}

/** Every icon of the catalogue, by its lucide name. */
export const ICONS = {
${entries}
} as const

/** Name of an icon the catalogue declares. */
export type IconName = keyof typeof ICONS
`
}

export interface EmojiViolation {
  file: string
  line: number
  glyph: string
}

/** Pictographic characters and the typographic glyphs a screen might use as an icon. */
const EMOJI = /[\p{Extended_Pictographic}←-⇿☀-➿⬀-⯿]/u

function sourceFilesOf(directory: string): string[] {
  if (!existsSync(directory)) return []
  const found: string[] = []
  for (const entry of readdirSync(directory)) {
    const path = join(directory, entry)
    if (statSync(path).isDirectory()) {
      found.push(...sourceFilesOf(path))
    } else if (entry.endsWith('.ts') || entry.endsWith('.tsx')) {
      found.push(path)
    }
  }
  return found
}

export function analyzeIconUsage(repositoryRoot: string): EmojiViolation[] {
  const violations: EmojiViolation[] = []
  for (const directory of SCANNED) {
    for (const file of sourceFilesOf(resolve(repositoryRoot, directory))) {
      const reported = relative(repositoryRoot, file).replaceAll('\\', '/')
      for (const [index, line] of readFileSync(file, 'utf8').split('\n').entries()) {
        const match = EMOJI.exec(line)
        if (match !== null) {
          violations.push({ file: reported, line: index + 1, glyph: match[0] })
        }
      }
    }
  }
  return violations
}

if (import.meta.main) {
  const repositoryRoot = resolve(import.meta.dir, '..')
  if (process.argv.includes('--generate')) {
    const path = join(repositoryRoot, 'packages', 'ui', 'src', 'icons', 'catalog.ts')
    writeFileSync(path, generateCatalogue(repositoryRoot))
    console.log(`generated ${CATALOGUE.length} icons into ${relative(repositoryRoot, path)}`)
  }

  const violations = analyzeIconUsage(repositoryRoot)
  for (const violation of violations) {
    console.error(
      `${violation.file}:${violation.line}: "${violation.glyph}" used as an icon; ` +
        'use an icon of the catalogue instead',
    )
  }
  console.log(
    violations.length === 0
      ? 'every icon comes from the catalogue'
      : `${violations.length} glyphs used as icons`,
  )
  if (violations.length > 0) process.exit(1)
}
